name: dcs-minimal
channels:
  - default
  - anaconda
dependencies:
  - pip:
    - pyarrow==0.13.0
    - azure==3.0.0
    - scipy
    - scikit-learn
    - spacy
    - nltk
    - gensim
    - textblob
    - allennlp
    - seaborn
    - flashtext
    - tensorflow
    - missingno
    - fancyimpute
  - pip
  - python=3.7.3
  - six=1.12.0
  - nomkl=3
  - ipython=7.4.0
  - numpy=1.16.2
  - pandas=0.24.2