name: py36
dependencies:
  - python=3.6
  - pip
  - cython
  - pandas
  - numpy
  - scipy
  - matplotlib
  - scikit-learn
  - seaborn
  - tqdm
  - nltk
  - h5py
  - pip:
    - joblib
    - stanfordcorenlp
    - gensim
    - textblob
  
  
  
  